trigger:
  branches:
    include:
      - refs/heads/*
      - refs/tags/*
pr:
  branches:
    include:
    - master

variables:
- group: pypi


resources:
  repositories:
    - repository: templates
      type: github
      name: bakdata/bakdata-project-templates
      endpoint: bot
      ref: improvements_template


stages:
  - template: azure/python/python-artifact.yml@templates